/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package users;

import admin.*;
import authentication.LOGIN;
import config.Session;
import config.db_connector;
import config.passwordHasher;
import static javax.management.remote.JMXConnectorFactory.connect;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Administrator
 */
public class addRental1 extends javax.swing.JFrame {

    /**
     * Creates new form REGISTER
     */
    public addRental1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        carname = new javax.swing.JTextField();
        number = new javax.swing.JTextField();
        cat = new javax.swing.JComboBox<>();
        update = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        rid = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        status = new javax.swing.JComboBox<>();
        cid = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        uid = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        payment = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 0, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 550));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel7.setText("Category:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel8.setText("Status:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        add.setBackground(new java.awt.Color(102, 0, 255));
        add.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 83, 30));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel13.setText("Rental ID:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel14.setText("Car Plate Number:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));
        jPanel1.add(carname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 333, 30));
        jPanel1.add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 333, 30));

        cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2 wheels", "4 wheels", "6 wheels", "10 wheels" }));
        jPanel1.add(cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 333, 30));

        update.setBackground(new java.awt.Color(102, 0, 255));
        update.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        update.setText("Update");
        update.setEnabled(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 83, 30));

        jButton3.setBackground(new java.awt.Color(102, 0, 255));
        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 83, 30));

        jButton4.setBackground(new java.awt.Color(102, 0, 255));
        jButton4.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 83, 30));

        jButton5.setBackground(new java.awt.Color(102, 0, 255));
        jButton5.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 83, 30));

        jButton6.setBackground(new java.awt.Color(102, 0, 255));
        jButton6.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jButton6.setText("Cancel");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 83, 30));

        rid.setEnabled(false);
        jPanel1.add(rid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 330, 30));

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel17.setText("Car Name:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 10));

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Occupied", "Pending" }));
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 330, 40));

        cid.setEnabled(false);
        jPanel1.add(cid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 310, 30));

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel16.setText("Car ID:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 20));

        uid.setEnabled(false);
        jPanel1.add(uid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 330, 30));

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel18.setText("User ID:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        payment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gcash", "BDO", "BPI" }));
        jPanel1.add(payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 333, 30));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel9.setText("Payment");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 20, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 390, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
 
    String Carname = carname.getText().trim();
    String Number = number.getText().trim();
    String Cat = cat.getSelectedItem() != null ? cat.getSelectedItem().toString().trim() : "";
    String Status = status.getSelectedItem() != null ? status.getSelectedItem().toString().trim() : "";
    String Payment = payment.getSelectedItem() != null ? payment.getSelectedItem().toString().trim() : "";
    String Carid = cid.getText().trim();
    Session sess = Session.getInstance();

   db_connector connect = new db_connector();


    if (Carname.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter the Car Name!", "Validation Error", JOptionPane.WARNING_MESSAGE);
    } else if (Number.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter the Car Number!", "Validation Error", JOptionPane.WARNING_MESSAGE);
    } else if (Cat.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please select a Category!", "Validation Error", JOptionPane.WARNING_MESSAGE);
    } else if (Status.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please select a Status!", "Validation Error", JOptionPane.WARNING_MESSAGE);
    } else if (Payment.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please select a Payment Method!", "Validation Error", JOptionPane.WARNING_MESSAGE);
        
    } else {
      
        try {
        // Check if car number already exists in rental table
        if (connect.fieldExists("rental", "c_number", Number)) {
            JOptionPane.showMessageDialog(null, "Car number already exists!", "Duplicate Entry", JOptionPane.WARNING_MESSAGE);
        } else {
            // Corrected SQL order and parameters
            String sql = "INSERT INTO rental (u_id, c_id, c_number, category, c_name, payment, status) VALUES (?, ?, ?, ?, ?, ?, ?)";
            int rowsInserted = connect.insertData(sql, sess.getId(), Carid, Number, Cat, Carname, Payment, Status);

            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(null, "Rental Registered Successfully!");

                new rental1 ().setVisible(true);this.dispose();

                JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(carname);
                if (frame != null) {
                    frame.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Rental registration failed!", "Insert Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Database Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } finally {
        connect.closeConnection();
    }
}

    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
  if (carname.getText().isEmpty() || number.getText().isEmpty() || 
    cat.getSelectedItem() == null || status.getSelectedItem() == null || 
    payment.getSelectedItem() == null || uid.getText().isEmpty() || 
    cid.getText().isEmpty() || rid.getText().isEmpty()) {

    JOptionPane.showMessageDialog(null, "All fields are required!", "Validation Error", JOptionPane.WARNING_MESSAGE);

} else {
    db_connector cdb = new db_connector();

    try {
        int rentalId;
        try {
            rentalId = Integer.parseInt(rid.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid Rental ID!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Check for duplicate car number excluding current rental record
        boolean carNumberExists = cdb.duplicateCheckExcludingCurrent(
            "rental", "c_number", number.getText(), "r_id", String.valueOf(rentalId)
        );

        if (carNumberExists) {
            JOptionPane.showMessageDialog(null, "Car number already exists in another rental record!", "Duplicate Error", JOptionPane.WARNING_MESSAGE);
        } else {
            int rowsUpdated = cdb.updateData(
                "UPDATE rental SET u_id = ?, c_id = ?, c_number = ?, category = ?, c_name = ?, payment = ?, status = ? WHERE r_id = ?",
                uid.getText().trim(),
                cid.getText().trim(),
                number.getText().trim(),
                cat.getSelectedItem().toString().trim(),
                carname.getText().trim(),
                payment.getSelectedItem().toString().trim(),
                status.getSelectedItem().toString().trim(),
                rentalId
            );

            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(null, "Rental updated successfully!");
                this.dispose();
                new rental1 ().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Update failed! Rental ID not found.", "Update Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Database Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } finally {
        cdb.closeConnection();
    }
}


    }//GEN-LAST:event_updateActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        rental1 s = new rental1();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
       new Selectcar1 ().setVisible(true); this.dispose();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addRental1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addRental1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addRental1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addRental1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addRental1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton add;
    public javax.swing.JTextField carname;
    public javax.swing.JComboBox<String> cat;
    public javax.swing.JTextField cid;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    public javax.swing.JTextField number;
    public javax.swing.JComboBox<String> payment;
    public javax.swing.JTextField rid;
    public javax.swing.JComboBox<String> status;
    public javax.swing.JTextField uid;
    public javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
